"""
Example notebook code for modeling and backtesting gas spreads.

Paste these cells into a Jupyter notebook (or run via `jupytext`) to fit
AR(1) models, generate trading signals, and backtest the spreads created
in `01_prepare_data`.
"""

# %%
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from src.backtester import backtest_spread
from src.metrics import summarize_backtest
from src.models import fit_ar1, half_life
from src.signals import generate_signal

# %% [markdown]
# ## Load spreads
# Ensure `data/processed/spreads.csv` exists (generated by `01_prepare_data`).

# %%
spreads_path = Path("data/processed/spreads.csv")
spreads = pd.read_csv(spreads_path, parse_dates=True, index_col="Date")
spreads.tail()

# %% [markdown]
# ## Fit AR(1), compute half-life, generate signals, and backtest
# Loop through each spread, collect model parameters, trading signals, and
# performance metrics.

# %%
plt.style.use("ggplot")

summaries = []
for spread_name in spreads.columns:
    series = spreads[spread_name]

    # Fit AR(1) model and compute half-life
    params = fit_ar1(series)
    hl = half_life(params["phi"])
    print(f"\n=== {spread_name} ===")
    print(f"phi: {params['phi']:.4f}")
    print(f"half-life: {hl:.2f} periods" if hl != float('inf') else "half-life: inf (non-stationary)")

    # Generate trading signal using default z-score thresholds
    signal, zscores = generate_signal(series, params["mu"], params["sigma"])

    # Backtest the spread strategy
    bt = backtest_spread(series, signal)

    # Summarize performance
    summary = summarize_backtest(bt, name=spread_name)
    summaries.append(summary)
    print(summary)

    # Plot spread level with z-scores and equity curve
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
    series.plot(ax=ax1, label=spread_name)
    ax1.set_title(f"{spread_name} spread")
    ax1.set_ylabel("EUR/MWh")
    ax1.legend(loc="upper left")

    ax1b = ax1.twinx()
    zscores.plot(ax=ax1b, color="gray", alpha=0.4, label="z-score")
    ax1b.axhline(2.0, color="red", linestyle="--", linewidth=1, label="entry +/-2")
    ax1b.axhline(-2.0, color="red", linestyle="--", linewidth=1)
    ax1b.axhline(0.5, color="blue", linestyle=":", linewidth=1, label="exit +/-0.5")
    ax1b.axhline(-0.5, color="blue", linestyle=":", linewidth=1)
    ax1b.set_ylabel("z-score")
    ax1b.legend(loc="upper right")

    bt["equity"].plot(ax=ax2, label="equity")
    ax2.set_title("Equity curve")
    ax2.set_ylabel("EUR")
    ax2.legend(loc="upper left")

    plt.tight_layout()
    plt.show()

# %% [markdown]
# ## Combined performance summary
# Collect all per-spread performance summaries into a single DataFrame for a
# quick overview.

# %%
summary_df = pd.DataFrame(summaries)
summary_df
